import { LinhaLivro } from '@/componentes/LinhaLivro';
import { Menu } from '@/componentes/Menu';
import type {NextPage} from 'next';
import Head from 'next/head';
import React, { useEffect, useState } from 'react';
import styles from '../styles/Home.module.css'

import _controleLivros from '../classes/controle/ControleLivros';

let controleLivros = new _controleLivros();









const LivroLista : NextPage = () => {

    const [livros, setLivros] = useState([]);
    let [carregado, setCarregado] = useState(false);

    function excluirLivro(codigo : string){

        return controleLivros.excluir(codigo).then((r) => {
            setCarregado(false);
            return r;
        })

    }

    useEffect(() => {
        if (carregado == false){
            controleLivros.obterLivros().then((data) => {
                setCarregado(true);
                setLivros(data);
            });
        }
    });

    return (
        <div className={styles.container}>
      <Head>
        <title>Loja Next</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Menu />
        <h1 className={styles.title}>Catálogo</h1>
        <main className={styles.main}>
        <table className="table">
                <thead className="table-dark">
                    <tr>
                        <th>Titulo</th>
                        <th>Resumo</th>
                        <th>Editora</th>
                        <th>Autores</th>
                    </tr>
                </thead>
                <tbody className="table-group-divider">
                {livros.map((item, index)=>{
                    return <LinhaLivro key={index} livro={item} excluir={excluirLivro}></LinhaLivro>
                })}
                </tbody>   
            </table> 
        </main>
    </div>
    )
}

export default LivroLista;